from summary_generation import *
from coref import *
from importance_ranking import *
from settings import *
from concept_maps_construction import *
from dbpedia_entity_extraction import extract_dbpedia_entities
from text_iri_merging import merge_text_iri
### ----------------------------------------------------------  SINGLE DOCUMNET SUMMARISATION ----------------------------------------------------------

if __name__ == '__main__':

    ### 2.1. TRAIN

    # generate summaries
    # parent_folder_path = WIKIPEDIA_TRAIN_DIR
    # output_folder_path = OUTPUT_DIR_SUMMARIES
    # summarize_folder(parent_folder_path, output_folder_path)

    # generate summaries with GPT
    parent_folder_path = CMAP_TRAIN_DIR
    output_folder_path = OUTPUT_DIR_SUMMARIES_GPT
    summarize_subfolders(parent_folder_path, output_folder_path)

    # coref
    # ----------> put the right path depending whether you want to use summaries generated by GPT or by LexRank

    # parent_folder_path = OUTPUT_DIR_SUMMARIES OR OUTPUT_DIR_SUMMARIES_GPT
    # output_folder_path = OUTPUT_DIR_COREF
    # perform_coreference_resolution(parent_folder_path, output_folder_path)

    # dbpedia entities
    # parent_folder_path = OUTPUT_DIR_SUMMARIES
    # output_folder_path = OUTPUT_DIR_SINGLE_DB_ENTITY
    # extract_dbpedia_entities(parent_folder_path, output_folder_path)

    # sentence importances
    # parent_folder_path = OUTPUT_DIR_COREF
    # output_folder_path = OUTPUT_IMPORTANCE_RANKING
    # process_parent_folder(parent_folder_path, output_folder_path)

    # extract triplets from summaries
    #  parent_folder_path = OUTPUT_IMPORTANCE_RANKING
    #  output_folder_path = OUTPUT_DIR_SINGLE_DOC_DISJOINT
    #  extract_triplets_from_summaries(parent_folder_path, output_folder_path)

    # integrate IRIs into triplets
    # parent_folder_path = OUTPUT_DIR_SINGLE_DOC_DISJOINT
    # mapping_folder_path = OUTPUT_DIR_SINGLE_DB_ENTITY
    # output_folder_path = OUTPUT_DIR_SINGLE_DOC_DISJOINT_WITH_IRIS
    # merge_text_iri(parent_folder_path, mapping_folder_path, output_folder_path)

    # generate graph
    # folder_path = OUTPUT_DIR_SINGLE_DOC_DISJOINT
    # output_folder_path = OUTPUT_DIR_GRAPH_SINGLE_DOC
    # generate_graph_from_txt_files(folder_path, output_folder_path)