from summary_generation import *
from triplets import *
from settings import *
from summary_aggregation import *
from concept_maps_construction import *
from evaluation_test_set import *
from coref import *
from importance_ranking import *
from dbpedia_entity_extraction import extract_dbpedia_entities
from text_iri_merging import merge_text_iri

### ---------------------------------------------------------- MULTIDOCUMENT SUMMARISATION ----------------------------------------------------------

if __name__ == '__main__':

    ### 1.1. TRAIN WITH FALKE CORPORA

## ----------------------------------------------------------

    #generate summaries
    # parent_folder_path = WIKI_TRAIN
    # output_folder_path = SUMMARIES_TRAIN_WIKI
    # summarize_subfolders(parent_folder_path,output_folder_path)
    # summarize_subfolders(WIKI,SUMMARIES_TRAIN_WIKI)

    # generate summaries with gpt
    # parent_folder_path = WIKI_TRAIN
    # output_folder_path = SUMMARIES_TRAIN_WIKI
    # summarize_subfolders(parent_folder_path, output_folder_path)

    #coref
    # ----------> put the right path depending whether you want to use summaries generated by GPT or by LexRank
    # parent_folder_path = SUMMARIES_TRAIN_WIKI
    # output_folder_path = OUTPUT_DIR_COREF_MULTIPLE_TRAIN_WIKI
    # perform_coreference_resolution(parent_folder_path, output_folder_path)

    # dbpedia entities
    # parent_folder_path = OUTPUT_DIR_COREF_MULTIPLE_TRAIN_WIKI
    # output_folder_path = OUTPUT_DIR_DB_ENTITY_WIKI
    # extract_dbpedia_entities(parent_folder_path, output_folder_path)

    #importance ranking
    # parent_folder_path = OUTPUT_DIR_COREF_MULTIPLE_TRAIN_WIKI
    # output_folder_path = IMPORTANCE_RANKING_TRAIN_WIKI
    # process_parent_folder(parent_folder_path,output_folder_path)

    # extract triplets from summaries
    # parent_folder_path = IMPORTANCE_RANKING_TRAIN_WIKI
    # output_folder_path = OUTPUT_DIR_TRIPLETS_DISJOINT_WIKI
    # extract_triplets_from_summaries(parent_folder_path, output_folder_path)

    # aggregate triplets
    # parent_folder_path_disjoint = OUTPUT_DIR_TRIPLETS_DISJOINT_WIKI
    # output_folder_path_aggregate = OUTPUT_DIR_TRIPLETS_AGGREGATE_WIKI
    # merge_files_by_prefix(parent_folder_path_disjoint, output_folder_path_aggregate)

    # generate graph
    # folder_path = OUTPUT_DIR_TRIPLETS_AGGREGATE_WIKI
    # output_folder_path = OUTPUT_DIR_GRAPH_WIKI
    # generate_graph_from_txt_files(folder_path, output_folder_path)

    ### 1.2. TEST

## ----------------------------------------------------------

    # generate summaries
    parent_folder_path = WIKI_TEST
    output_folder_path = SUMMARIES_TEST_WIKI
    summarize_subfolders(parent_folder_path,output_folder_path)

    # generate summaries gpt
    parent_folder_path = WIKI_TEST
    output_folder_path = SUMMARIES_TEST_GPT_WIKI
    summarize_subfolders(parent_folder_path, output_folder_path)

    # coref
    # ----------> put the right path depending whether you want to use summaries generated by GPT or by LexRank
    parent_folder_path = SUMMARIES_TEST_GPT_WIKI
    output_folder_path = OUTPUT_DIR_COREF_MULTIPLE_TEST_WIKI
    perform_coreference_resolution(parent_folder_path, output_folder_path)

    # sentence importances
    parent_folder_path = OUTPUT_DIR_COREF_MULTIPLE_TEST_WIKI
    output_folder_path = IMPORTANCE_RANKING_TEST_WIKI
    process_parent_folder(parent_folder_path,output_folder_path)

    # extract triplets from summaries
    parent_folder_path = IMPORTANCE_RANKING_TEST_WIKI
    output_folder_path = OUTPUT_DIR_TRIPLETS_DISJOINT_TEST_WIKI
    extract_triplets_from_summaries(parent_folder_path, output_folder_path)

    # # aggregate triplets
    parent_folder_path_disjoint = OUTPUT_DIR_TRIPLETS_DISJOINT_TEST_WIKI
    output_folder_path_aggregate = OUTPUT_DIR_TRIPLETS_AGGREGATE_TEST_WIKI
    merge_files_by_prefix(parent_folder_path_disjoint, output_folder_path_aggregate)

    # generate graph
    folder_path = OUTPUT_DIR_TRIPLETS_AGGREGATE_TEST_WIKI
    output_folder_path = OUTPUT_DIR_GRAPH_TEST_WIKI
    generate_graph_from_txt_files(folder_path, output_folder_path)

## ----------------------------------------------------------

### 1.3. METEOR AND ROUGE

    input_folder_path = OUTPUT_DIR_TRIPLETS_AGGREGATE_TEST_WIKI
    gold_folder_path = WIKI_FINAL_TEST_DIR
    output_folder_path = OUTPUT_DIR_EVALUATION_CSV_WIKI
    compute_metrics(input_folder_path, gold_folder_path, output_folder_path)

    # # METEOR AND ROUGE CHATGPT
    # input_folder_path = SUMMARIES
    # output_folder_path = CMAP_TEST_GPT
    # aggregate_txt_files(input_folder_path, output_folder_path)
